spring:
  application:
    name: food-delivery

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.portfolio.fooddelivery: debug

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans

  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

jwt:
  secret: "dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi1pbi1mb29kLWRlbGl2ZXJ5LWFwcGxpY2F0aW9u"
  token-validity-in-seconds: 86400  # 24??